---
# tasks file for nginx

- name: Add nginx repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo owner=root group=root mode=0644

- name: Install nginx
  yum: name=nginx state=present

- name: State default.conf
  stat: path=/etc/nginx/conf.d/default.conf
  register: default_conf

- name: Trash default.conf
  command: mv /etc/nginx/conf.d/default.conf /root/garbage/default.conf
  when: default_conf.stat.exists

- name: Install nginx configuration files
  copy: src={{ item.file }} dest={{ item.path }} owner=root group=root mode=0644
  with_items:
    - { file: 'nginx.conf', path: '/etc/nginx/nginx.conf' }
    - { file: 'moodle.conf', path: '/etc/nginx/conf.d/moodle.conf' }

- name: Enable and start nginx service
  systemd: name=nginx enabled=yes state=started
